#!/usr/bin/env node
/* ============================================================
   Give every seeded SKU its own crawlable page, and keep the
   sitemap and the FAQ's structured data honest.

   Why this exists: the site is static files on GoDaddy with no
   way to render anything server-side, and until now every product
   lived at product.html?id=N — one file, one <title>, one
   description, one canonical, nine products. Search engines saw a
   single thin page called "Product". The compound names, which are
   the only queries that matter commercially, had nowhere to land.

   So the pages are written here instead, once, from the same
   catalog the site already ships:

     1. <slug>.html per SKU, cloned from product.html with its
        <head> and its detail card replaced by that product's real
        facts — in HTML, so a crawler that never runs a line of
        JavaScript still reads the name, size, lot, price, specs
        and COA. main.js then overwrites the same card at runtime
        with the interactive version (add-to-cart, gallery, COA
        lightbox). Same pattern as tools/build-jsonld.js: the baked
        copy is for crawlers, the live copy is for people, and both
        come from this catalog so they cannot disagree.
     2. PRODUCT_PAGES in js/products-data.js, so productHref() in
        main.js links to those pages everywhere on the site.
     3. sitemap.xml, with lastmod read off the files themselves —
        the hand-written one had been claiming 2026-07-16 for
        months.
     4. FAQPage structured data baked into faq.html from the
        questions already on it.

   Run after changing js/products-data.js, a price, or the FAQ:

       node tools/build-seo.js

   Prices and stock come from the SEED catalog, which is what the
   server is seeded from. If a price has since changed in admin
   only, sync the seed first — a baked price that disagrees with
   the page is a Merchant-listing penalty, which is worse than no
   markup at all. Same rule as build-jsonld.js, same reason.
   ============================================================ */

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const DATA = path.join(ROOT, 'js', 'products-data.js');
const MAIN = path.join(ROOT, 'js', 'main.js');
const TEMPLATE = path.join(ROOT, 'product.html');
const FAQ = path.join(ROOT, 'faq.html');
const SITEMAP = path.join(ROOT, 'sitemap.xml');
const ORIGIN = 'https://evernovalife.com/';

/* Stamped into every generated file so a later run can tell its own output
   apart from a hand-written page and clean up SKUs that have gone. */
const STAMP = '<!-- This file is generated by tools/build-seo.js — edit product.html or js/products-data.js instead. -->';

const HEAD_BEGIN = '<!-- BEGIN seo-head · replaced per SKU by tools/build-seo.js — do not edit in a generated page -->';
const HEAD_END = '<!-- END seo-head -->';
const DETAIL_BEGIN = '<!-- BEGIN seo-detail · replaced per SKU by tools/build-seo.js — do not edit in a generated page -->';
const DETAIL_END = '<!-- END seo-detail -->';
const PAGES_BEGIN = '/* BEGIN product-pages · generated by tools/build-seo.js — do not edit by hand */';
const PAGES_END = '/* END product-pages */';
const FAQ_BEGIN = '<!-- BEGIN ld-faq · generated by tools/build-seo.js — do not edit by hand -->';
const FAQ_END = '<!-- END ld-faq -->';

/* ---------- small helpers ---------- */

function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/* URL-safe, readable, and stable: the slug IS the published address, so a
   change here orphans a page that may already be indexed. Rename only
   deliberately, and redirect the old path when you do. */
function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/\+/g, ' plus ')
    .replace(/&/g, ' and ')
    .replace(/[()]/g, ' ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/* The size belongs in the address — people search "retatrutide 10mg", not
   "retatrutide" — except where the name already carries it, which would give
   us hgh-36-iu-36-iu.html. */
function productSlug(p) {
  const name = slugify(p.name);
  const size = p.quantity ? slugify(p.quantity) : '';
  if (!size || name === size || name.endsWith('-' + size)) return name;
  return name + '-' + size;
}

/* Meta descriptions get cut by the search engine at roughly 155 characters.
   Cutting on a word boundary here means we choose where, rather than being
   left with a half word and an ellipsis nobody wrote. */
function metaDescription(p) {
  const LIMIT = 155;
  let text = String(p.description || '').replace(/\s+/g, ' ').trim();
  if (text.length > LIMIT) {
    const cut = text.slice(0, LIMIT);
    const lastSpace = cut.lastIndexOf(' ');
    text = (lastSpace > 80 ? cut.slice(0, lastSpace) : cut).replace(/[,;:.\s]+$/, '') + '…';
  }
  return text;
}

function pageTitle(p) {
  const size = p.quantity ? ` ${p.quantity}` : '';
  return `${p.name}${size} — Lot-Traceable Research Material | Ever Nova Life`;
}

/* products-data.js is a plain browser script declaring consts. Run it in a
   throwaway context and read the globals out, rather than duplicating the
   catalog here where it could drift. Same loader as build-jsonld.js. */
function loadCatalog() {
  const src = fs.readFileSync(DATA, 'utf8');
  const sandbox = { window: {}, document: undefined };
  vm.createContext(sandbox);
  vm.runInContext(src + '\n;globalThis.__out = { PRODUCTS };', sandbox);
  const out = sandbox.__out || {};
  if (!Array.isArray(out.PRODUCTS) || !out.PRODUCTS.length) {
    throw new Error('No PRODUCTS array found in js/products-data.js');
  }
  return out.PRODUCTS;
}

/* The vial cache-buster lives in main.js and is bumped when photos are
   re-published. Read it rather than keeping a second copy that goes stale. */
function vialVersion() {
  const m = fs.readFileSync(MAIN, 'utf8').match(/const VIAL_V\s*=\s*(\d+)/);
  return m ? m[1] : '1';
}

function replaceBetween(text, begin, end, replacement, where) {
  const start = text.indexOf(begin);
  const stop = text.indexOf(end);
  if (start === -1 || stop === -1) {
    throw new Error(`Could not find the markers in ${where}. Expected:\n  ${begin}\n  ${end}`);
  }
  return text.slice(0, start) + replacement + text.slice(stop + end.length);
}

/* ---------- structured data ---------- */

/* Must stay in step with productSchema() in js/main.js — the runtime pass
   overwrites this node with the live catalog's version, and the two
   disagreeing is the failure mode. */
function productSchema(p, url) {
  const specs = p.specs || {};
  const props = Object.keys(specs)
    .filter(k => specs[k])
    .map(k => ({ '@type': 'PropertyValue', name: k, value: String(specs[k]) }));

  // A year out: the convention for a price with no planned end date.
  const validUntil = new Date(Date.now() + 365 * 24 * 3600 * 1000).toISOString().slice(0, 10);

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    '@id': url + '#product',
    name: p.name,
    description: p.description,
    image: `${ORIGIN}assets/vials/${p.id}.webp`,
    sku: p.lot || `ENL-${p.id}`,
    productID: String(p.id),
    category: p.categoryName || '',
    brand: { '@type': 'Brand', name: 'Ever Nova Life' },
    offers: {
      '@type': 'Offer',
      url,
      priceCurrency: 'USD',
      price: Number(p.price).toFixed(2),
      priceValidUntil: validUntil,
      itemCondition: 'https://schema.org/NewCondition',
      // The seed carries no live count, so this is the published on/off state.
      // The runtime pass corrects it from the real stock figure.
      availability: 'https://schema.org/' + (p.inStock === false ? 'OutOfStock' : 'InStock'),
      seller: { '@type': 'Organization', name: 'Ever Nova Life', '@id': ORIGIN + '#org' }
    }
  };
  if (props.length) schema.additionalProperty = props;
  return schema;
}

function breadcrumbSchema(p, url) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: ORIGIN },
      { '@type': 'ListItem', position: 2, name: 'Products', item: ORIGIN + 'products.html' },
      { '@type': 'ListItem', position: 3, name: p.name, item: url }
    ]
  };
}

function ldScript(id, obj) {
  return `  <script type="application/ld+json" id="${id}">\n  ` +
    JSON.stringify(obj, null, 2).split('\n').join('\n  ') + '\n  </script>';
}

/* ---------- the two replaced blocks ---------- */

function headBlock(p, slug) {
  const url = ORIGIN + slug + '.html';
  const title = escapeHtml(pageTitle(p));
  const desc = escapeHtml(metaDescription(p));
  const image = `${ORIGIN}assets/vials/${p.id}.webp`;

  return [
    HEAD_BEGIN,
    `  <title>${title}</title>`,
    `  <meta name="description" content="${desc}">`,
    `  <link rel="canonical" href="${url}">`,
    '  <meta property="og:type" content="product">',
    '  <meta property="og:site_name" content="Ever Nova Life">',
    `  <meta property="og:title" content="${title}">`,
    `  <meta property="og:description" content="${desc}">`,
    `  <meta property="og:url" content="${url}">`,
    `  <meta property="og:image" content="${image}">`,
    '  <meta name="twitter:card" content="summary_large_image">',
    `  <meta name="twitter:title" content="${title}">`,
    `  <meta name="twitter:description" content="${desc}">`,
    `  <meta name="twitter:image" content="${image}">`,
    // Tells main.js which SKU this file is, so the detail view no longer
    // depends on a ?id= that this URL does not carry.
    `  <script>window.ENL_PRODUCT_ID = ${JSON.stringify(String(p.id))};</script>`,
    ldScript('ld-product', productSchema(p, url)),
    ldScript('ld-breadcrumb', breadcrumbSchema(p, url)),
    '  ' + HEAD_END
  ].join('\n');
}

/* The crawler-facing copy of the product. Deliberately plain: no buttons, no
   state, nothing that needs JavaScript to mean anything — every fact that
   belongs in the index, in markup, above the point where main.js takes over.
   Class names match the live markup so it looks right in the half-second
   before that happens, and to a visitor with JS off. */
function detailBlock(p, vialV) {
  const specsRows = Object.entries(p.specs || {})
    .filter(([, v]) => v)
    .map(([k, v]) => `            <tr><td>${escapeHtml(k)}</td><td>${escapeHtml(v)}</td></tr>`)
    .join('\n');

  const coa = p.coa || {};
  let coaBlock;
  if (coa.status === 'available') {
    const rows = [
      ['Laboratory', coa.lab],
      ['Report', coa.reportId],
      ['Batch', coa.batch],
      ['Method', coa.method],
      ['Test date', coa.testDate],
      ['Report date', coa.reportDate],
      ['Purity', coa.purity],
      ['Measured content', coa.content]
    ].filter(([, v]) => v)
      .map(([k, v]) => `            <tr><td>${escapeHtml(k)}</td><td>${escapeHtml(v)}</td></tr>`)
      .join('\n');
    coaBlock = [
      '        <h2>Certificate of Analysis</h2>',
      `        <p>This lot was analyzed by an independent laboratory. The full report is published in our <a href="quality.html#coa-library">COA Library</a>.</p>`,
      '        <table class="specs-table"><tbody>',
      rows,
      '        </tbody></table>',
      coa.note ? `        <p><strong>Scope of the report on file:</strong> ${escapeHtml(coa.note)}</p>` : ''
    ].filter(Boolean).join('\n');
  } else {
    const label = coa.status === 'pending' ? 'pending' : 'not provided';
    coaBlock = [
      '        <h2>Certificate of Analysis</h2>',
      `        <p>Documentation for this lot is ${label}. Published reports for other lots are in our <a href="quality.html#coa-library">COA Library</a>.</p>`
    ].join('\n');
  }

  const price = Number(p.price).toFixed(2);
  const meta = [p.quantity, p.purity, p.lot ? 'Lot ' + p.lot : ''].filter(Boolean)
    .map(v => `<span>${escapeHtml(v)}</span>`).join('<span>•</span>');

  return [
    DETAIL_BEGIN,
    '        <!-- Generated from js/products-data.js. main.js replaces this with the',
    '             interactive detail view once the catalog loads; until then (and for',
    '             any crawler that never runs it) these are the product\'s real facts. -->',
    '        <div class="product-detail-side">',
    '          <div class="product-detail-media glass">',
    `            <img src="assets/vials/${p.id}.webp?v=${vialV}"`,
    `                 srcset="assets/vials/${p.id}-sm.webp?v=${vialV} 420w, assets/vials/${p.id}.webp?v=${vialV} 630w"`,
    '                 sizes="(max-width: 700px) 60vw, 420px"',
    '                 width="630" height="1380" fetchpriority="high" decoding="async"',
    `                 alt="${escapeHtml(p.name)} ${escapeHtml(p.quantity || '')} vial, supplied lyophilized for in-vitro research">`,
    '          </div>',
    '        </div>',
    '        <div class="product-detail-info">',
    `          <span class="product-cat">${escapeHtml(p.categoryName || '')}</span>`,
    `          <h1>${escapeHtml(p.name)}</h1>`,
    `          <div class="product-meta">${meta}</div>`,
    '          <div class="detail-price-row">',
    `            <span class="detail-price gradient-text">$${price}</span>`,
    `            <span class="stock-pill">${p.inStock === false ? 'Out of stock' : 'In stock'}</span>`,
    '          </div>',
    `          <p class="detail-desc">${escapeHtml(p.description)}</p>`,
    '          <h2>Specifications</h2>',
    '          <table class="specs-table"><tbody>',
    specsRows,
    '          </tbody></table>',
    coaBlock,
    `          <p><strong>For qualified in-vitro research and laboratory use only.</strong> Not for human or animal use. See <a href="research-accounts.html">Research Accounts</a> and the <a href="terms.html#disclaimer">research-use notice</a>.</p>`,
    '          <p><a class="btn btn-primary" href="products.html">Browse the full catalog</a></p>',
    '        </div>',
    '        ' + DETAIL_END
  ].filter(l => l !== '').join('\n');
}

/* ---------- writers ---------- */

function writeProductPages(products, vialV) {
  const template = fs.readFileSync(TEMPLATE, 'utf8');
  const slugs = new Map();

  for (const p of products) {
    const slug = productSlug(p);
    if (slugs.has(slug)) {
      throw new Error(`Two products slugify to "${slug}" (ids ${slugs.get(slug)} and ${p.id}). Rename one.`);
    }
    slugs.set(slug, p.id);

    let html = replaceBetween(template, HEAD_BEGIN, HEAD_END, headBlock(p, slug), 'product.html <head>');
    html = replaceBetween(html, DETAIL_BEGIN, DETAIL_END, detailBlock(p, vialV), 'product.html #productDetail');
    html = html.replace(/(id="detailCrumb">)[^<]*(<\/span>)/, `$1${escapeHtml(p.name)}$2`);
    html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + STAMP);

    fs.writeFileSync(path.join(ROOT, slug + '.html'), html, 'utf8');
  }

  // A SKU that has gone should take its page with it, or the sitemap and the
  // index keep pointing at a product nobody can buy.
  let removed = 0;
  for (const file of fs.readdirSync(ROOT)) {
    if (!file.endsWith('.html') || slugs.has(file.replace(/\.html$/, ''))) continue;
    const full = path.join(ROOT, file);
    if (!fs.statSync(full).isFile()) continue;
    if (fs.readFileSync(full, 'utf8').includes(STAMP)) {
      fs.unlinkSync(full);
      removed++;
    }
  }

  return { slugs, removed };
}

function writeProductPagesMap(slugs) {
  const entries = [...slugs.entries()]
    .sort((a, b) => a[1] - b[1])
    .map(([slug, id]) => `  ${id}: '${slug}'`)
    .join(',\n');
  const block = `${PAGES_BEGIN}\nconst PRODUCT_PAGES = {\n${entries}\n};\n${PAGES_END}`;
  const src = fs.readFileSync(DATA, 'utf8');
  fs.writeFileSync(DATA, replaceBetween(src, PAGES_BEGIN, PAGES_END, block, 'js/products-data.js'), 'utf8');
}

/* Everything a stranger should be able to find, and nothing else. Anything
   behind a login, tied to one order, or only useful mid-checkout stays out —
   robots.txt already blocks those, and listing them here would contradict it. */
const STATIC_PAGES = [
  ['', 1.0],
  ['products.html', 0.9],
  ['quality.html', 0.9],
  ['research-accounts.html', 0.8],
  ['about.html', 0.7],
  ['contact.html', 0.7],
  ['faq.html', 0.7],
  ['shipping.html', 0.6],
  ['returns.html', 0.6],
  ['order-status.html', 0.5],
  ['terms.html', 0.4],
  ['privacy.html', 0.4]
];

function lastmod(file) {
  const full = path.join(ROOT, file || 'index.html');
  try {
    return fs.statSync(full).mtime.toISOString().slice(0, 10);
  } catch (e) {
    return new Date().toISOString().slice(0, 10);
  }
}

function writeSitemap(slugs) {
  const urls = STATIC_PAGES.map(([file, priority]) => ({
    loc: ORIGIN + file,
    lastmod: lastmod(file),
    priority
  }));

  for (const [slug] of [...slugs.entries()].sort((a, b) => a[1] - b[1])) {
    urls.push({ loc: `${ORIGIN}${slug}.html`, lastmod: lastmod(slug + '.html'), priority: 0.8 });
  }

  const body = urls.map(u =>
    '  <url>\n' +
    `    <loc>${u.loc}</loc>\n` +
    `    <lastmod>${u.lastmod}</lastmod>\n` +
    `    <priority>${u.priority.toFixed(1)}</priority>\n` +
    '  </url>'
  ).join('\n');

  fs.writeFileSync(SITEMAP,
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!-- Generated by tools/build-seo.js — do not edit by hand. -->\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    body + '\n</urlset>\n', 'utf8');

  return urls.length;
}

/* The questions are already written on faq.html; this only restates them in a
   form a search engine can quote. Reading them back out of the page means the
   markup can never claim an answer the page does not give.

   ponytail: regex over our own regular markup, not a parser. If the FAQ ever
   stops being a flat list of .faq-item > .faq-q + .faq-a, parse it properly. */
function writeFaqSchema() {
  const src = fs.readFileSync(FAQ, 'utf8');
  const items = [...src.matchAll(/<button class="faq-q">([\s\S]*?)<\/button>\s*<div class="faq-a">([\s\S]*?)<\/div>\s*<\/div>/g)];

  if (!items.length) {
    console.warn('! No .faq-item blocks matched in faq.html — FAQ schema left as it was.');
    return 0;
  }

  const strip = (html) => html
    .replace(/<span class="chevron">[\s\S]*?<\/span>/g, '')
    .replace(/<[^>]*>/g, ' ')
    .replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    // Dropping a tag leaves the space that sat around it, so a sentence ending
    // in a link comes out as "see our returns page ." unless it is closed up.
    .replace(/\s+([,.;:!?)])/g, '$1')
    .replace(/\(\s+/g, '(')
    .trim();

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    '@id': ORIGIN + 'faq.html#faq',
    mainEntity: items.map(([, q, a]) => ({
      '@type': 'Question',
      name: strip(q),
      acceptedAnswer: { '@type': 'Answer', text: strip(a) }
    })).filter(q => q.name && q.acceptedAnswer.text)
  };

  const block = FAQ_BEGIN + '\n' + ldScript('ld-faq', schema) + '\n  ' + FAQ_END;
  fs.writeFileSync(FAQ, replaceBetween(src, FAQ_BEGIN, FAQ_END, block, 'faq.html'), 'utf8');
  return schema.mainEntity.length;
}

function main() {
  const products = loadCatalog();
  const vialV = vialVersion();

  const { slugs, removed } = writeProductPages(products, vialV);
  writeProductPagesMap(slugs);
  const urlCount = writeSitemap(slugs);
  const faqCount = writeFaqSchema();

  console.log(`Wrote ${slugs.size} product pages${removed ? ` (removed ${removed} stale)` : ''}:`);
  for (const [slug, id] of [...slugs.entries()].sort((a, b) => a[1] - b[1])) {
    console.log(`  ${String(id).padStart(2)} → /${slug}.html`);
  }
  console.log(`Wrote sitemap.xml (${urlCount} URLs) and FAQPage schema (${faqCount} questions).`);
  console.log('Vial images referenced at ?v=' + vialV + '.');
}

main();
