#!/usr/bin/env node
/* ============================================================
   Bake the catalog's Product structured data into products.html

   Why a build step at all: the catalog grid is painted from the
   API at runtime, and the site is served as static files from
   GoDaddy with no way to render anything server-side. Google does
   execute JS, but it is a second pass that isn't guaranteed — and
   Bing and the AI crawlers largely don't. So the shelf gets
   written into the HTML once, here, and the page's own
   initCatalogSchema() overwrites the same <script id="ld-catalog">
   at runtime with whatever the live API says.

   Same @id in both copies, so they are one node and not two
   competing descriptions of the same list.

   Run after changing js/products-data.js (or a price):
       node tools/build-jsonld.js

   Prices and availability come from the SEED catalog, which is
   what the server is seeded from. If a price has since been
   changed in admin only, re-run this after syncing the seed —
   a stale baked price is worse than none, because a mismatch
   between markup and page is a Merchant-listing penalty.
   ============================================================ */

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const DATA = path.join(ROOT, 'js', 'products-data.js');
const PAGE = path.join(ROOT, 'products.html');
const ORIGIN = 'https://evernovalife.com/';

const BEGIN = '<!-- BEGIN ld-catalog · generated by tools/build-jsonld.js — do not edit by hand -->';
const END = '<!-- END ld-catalog -->';

/* products-data.js is a plain browser script declaring consts. Run it in a
   throwaway context and read the two globals out, rather than duplicating the
   catalog here where it could drift. */
function loadCatalog() {
  const src = fs.readFileSync(DATA, 'utf8');
  const sandbox = { window: {}, document: undefined };
  vm.createContext(sandbox);
  vm.runInContext(src + '\n;globalThis.__out = { PRODUCTS, CATEGORIES };', sandbox);
  const out = sandbox.__out || {};
  if (!Array.isArray(out.PRODUCTS) || !out.PRODUCTS.length) {
    throw new Error('No PRODUCTS array found in js/products-data.js');
  }
  return out.PRODUCTS;
}

/* Must stay in step with productSchema() in js/main.js — the runtime copy
   overwrites this one, and the two disagreeing is the failure mode. */
function productSchema(p) {
  const url = `${ORIGIN}product.html?id=${p.id}`;
  const specs = p.specs || {};
  const props = Object.keys(specs)
    .filter(k => specs[k])
    .map(k => ({ '@type': 'PropertyValue', name: k, value: String(specs[k]) }));

  // A year out: the convention for a price with no planned end date.
  const validUntil = new Date(Date.now() + 365 * 24 * 3600 * 1000).toISOString().slice(0, 10);

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    '@id': url + '#product',
    name: p.name,
    description: p.description,
    image: `${ORIGIN}assets/vials/${p.id}.webp`,
    sku: p.lot || `ENL-${p.id}`,
    productID: String(p.id),
    category: p.categoryName || '',
    brand: { '@type': 'Brand', name: 'Ever Nova Life' },
    offers: {
      '@type': 'Offer',
      url,
      priceCurrency: 'USD',
      price: Number(p.price).toFixed(2),
      priceValidUntil: validUntil,
      itemCondition: 'https://schema.org/NewCondition',
      // The seed carries no live count, so this is the published on/off state.
      // The runtime pass corrects it from the real stock figure.
      availability: 'https://schema.org/' + (p.inStock === false ? 'OutOfStock' : 'InStock'),
      seller: { '@type': 'Organization', name: 'Ever Nova Life', '@id': ORIGIN + '#org' }
    }
  };
  if (props.length) schema.additionalProperty = props;
  return schema;
}

function build(products) {
  const list = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    '@id': ORIGIN + 'products.html#catalog',
    name: 'Ever Nova Life research materials',
    numberOfItems: products.length,
    itemListElement: products.map((p, i) => {
      // The list already declares the context; repeating it per item is noise.
      const { '@context': _ctx, ...item } = productSchema(p);
      return { '@type': 'ListItem', position: i + 1, item };
    })
  };
  return BEGIN + '\n' +
    '  <script type="application/ld+json" id="ld-catalog">\n  ' +
    JSON.stringify(list, null, 2).split('\n').join('\n  ') + '\n  </script>\n  ' +
    END;
}

function main() {
  const products = loadCatalog();
  const block = build(products);
  let html = fs.readFileSync(PAGE, 'utf8');

  const start = html.indexOf(BEGIN);
  const stop = html.indexOf(END);
  if (start === -1 || stop === -1) {
    console.error(`Could not find the markers in products.html.\nAdd this to <head>:\n\n  ${BEGIN}\n  ${END}\n`);
    process.exit(1);
  }
  html = html.slice(0, start) + block + html.slice(stop + END.length);

  // utf8, no BOM, existing line endings left as they are.
  fs.writeFileSync(PAGE, html, 'utf8');
  console.log(`Baked ${products.length} products into products.html (#ld-catalog).`);
}

main();
